/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "AllPassLoopReverb.h"
#include "echoForBrowser.h"
#include "EchoplexDelay.h"
#include "FlangerFeedback.h"
#include "FuzzTone.h"
#include "granulator.h"
#include "GritAmp.h"
#include "KorgHpf2Poles.h"
#include "KorgLpf2Poles.h"
#include "MicroShifter.h"
#include "MoogLpf2Poles.h"
#include "mp3Compressor.h"
#include "mp3Reverb.h"
#include "OberheimBpf2Poles.h"
#include "OberheimBpf4Poles.h"
#include "OberheimHpf2Poles.h"
#include "OberheimHpf4Poles.h"
#include "OberheimLpf2Poles.h"
#include "OberheimLpf4Poles.h"
#include "Phaser.h"
#include "QuadraticDistortion.h"
#include "RnboLooper2.h"
#include "RnboReverseDelay.h"
#include "RnboTubeTapeSaturation.h"
#include "SallenKeyBpf.h"
#include "SallenKeyHpf.h"
#include "SallenKeyLpf.h"
#include "SaturatorWavefolding.h"
#include "SoftClip.h"
#include "TransientShaper.h"

// Include compiled network files ------------------

#include "AutoPanner.h"
#include "Compressor.h"
#include "Detuner.h"
#include "Filters_networkdata.h"
#include "Flanger.h"
#include "GlistenReverb.h"
#include "Grains.h"
#include "HazeDistortion.h"
#include "InfiniteReverb.h"
#include "Korg_ScriptFx.h"
#include "Looper.h"
#include "Moog_ScriptFx.h"
#include "Oberheim_ScriptFx.h"
#include "Phaser_Script_networkdata.h"
#include "ReverseDelay.h"
#include "SallenKey_ScriptFx.h"
#include "SaturatorDigital.h"
#include "SaturatorModern.h"
#include "SaturatorVintage.h"
#include "ShredDistortion.h"
#include "SlapbackDelay.h"
#include "SoftClip_networkdata.h"
#include "TransientShaper_networkdata.h"
#include "TwistDelay.h"
#include "Widener.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

